### ISSUE TITLE
When using make, says include file doesn't exist

### ISSUE THREAD

**Issue by e-luo** [intel-iot-devkit/intruder-detector#1]
intruder-detector/application/src/main.cpp:36:10: fatal error: ie_icnn_net_reader.h: No such file or directory
 #include <ie_icnn_net_reader.h>

I've tried searching online what ie_icnn_net_reader is for, but I didn't find anything. Any advice will be appreciated, thanks in advance.

**Comment by Propanu** [comment]
Hi @e-luo this demo was developed with an older version of the OpenVINO toolkit thus I think the last section in [this article](https://software.intel.com/en-us/blogs/2018/05/14/how-to-port-your-application-from-intelr-computer-vision-sdk-2017-r3-beta-to-intelr) can help until this repo is updated.

**Comment by e-luo** [comment]
@Propanu, thanks for the help. I tried changing `#include <ie_icnn_net_reader.h>` to `#include <cpp/ie_cnn_net_reader.h>`, however the same error would show up.

`intruder-detector/application/src/main.cpp:36:10: fatal error: cpp/ie_nn_net_reader.h: No such file or directory
 #include <cpp/ie_nn_net_reader.h>`

Below is an image of the contents in the `/opt/intel/computer_vision_sdk_2018.3.343/inference_engine/include/cpp` directory:

![image](https://user-images.githubusercontent.com/12617612/48445309-212d9900-e74b-11e8-87d6-91eb067a3cf5.png)

**Comment by e-luo** [comment]
I found the problem; I need to first type source env.sh in the root directory before proceeding. @Propanu, thanks for the help.

I am encountering new problems though, I keep getting this error message: warning: libavcodec-ffmpeg.so.56, needed by /opt/intel/computer_vision_sdk_2018.3.343/opencv/lib/libopencv_videoio.so.3.4.3, not found

However, when I type ffmpeg in the terminal, I get:
`ffmpeg version 2.7.7 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: 
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
Hyper fast Audio and Video encoder
`
I have the correct versions. The ffmpeg is in /usr/bin. Why can't openvino see it?
